### ISSUE TITLE
Gulp 4.0.0-alpha.3 can't parse config bundle file

### ISSUE THREAD

**Issue by itlessons** [areusjs/gulp-bundle-assets#103]
After update to Gulp 4.0.0-alpha.3 code throw error:
> Failed to parse config file: /path/bundle.config.js
Error: Configuration file should be in the form "{ bundle: {}, copy: {} }"
 at new Config (/path/node_modules/gulp-bundle-assets/lib/model/config.js:26:11)
    at Writable._write (/path/node_modules/gulp-bundle-assets/index.js:38:16)
    at doWrite (/path/node_modules/gulp-bundle-assets/node_modules/readable-stream/lib/_stream_writable.js:319:12)
    at writeOrBuffer (/path/node_modules/gulp-bundle-assets/node_modules/readable-stream/lib/_stream_writable.js:305:5)
    at Writable.write (/path/node_modules/gulp-bundle-assets/node_modules/readable-stream/lib/_stream_writable.js:232:11)
.....

If downgrade to Gulp 4.0.0-alpha.2 works fine like this:
`"gulp": "github:gulpjs/gulp#6d71a65",`

I guess need update vinyl to 2.1:
[https://github.com/gulpjs/gulp/issues/2065](https://github.com/gulpjs/gulp/issues/2065)
[https://github.com/gulpjs/vinyl-fs/issues/288](https://github.com/gulpjs/vinyl-fs/issues/288)

**Comment by chmontgomery** [comment]
`gulp-bundle-assets` was never intended to work with gulp 4. `gulp-bundle-assets` should still be using gulp 3 under the covers even if you're using a gulp 4 `gulpfile`. I bet there's a shared dependency that breaks things since I never shrinkwrapped (or package locked) this module.

I don't have any plans to update this module for gulp 4 support. sorry.
